In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [61]:
data = pd.read_csv("titanic.csv");

#most values here are null so i dropped them
data.drop(['Cabin'], axis=1, inplace=True);

#i filled the empty age values with the median age instead
data['Age'] = data['Age'].fillna(data['Age'].median())
data.info()

data['Embarked'] = data['Embarked'].fillna(
    data['Embarked'].mode()[0]
)

data.drop(
    ['PassengerId', 'Name', 'Ticket'],
    axis=1,
    inplace=True
)

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 76.7 KB

In [62]:
data

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female  28.0      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [63]:
print(data.isnull().sum())

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [64]:
X = data.drop('Survived', axis=1)
y = data['Survived']

In [65]:
X

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female  28.0      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [66]:
X = pd.get_dummies(X, drop_first=True)

In [67]:
X

     Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  Embarked_S
0         3  22.0      1      0   7.2500      True       False        True
1         1  38.0      1      0  71.2833     False       False       False
2         3  26.0      0      0   7.9250     False       False        True
3         1  35.0      1      0  53.1000     False       False        True
4         3  35.0      0      0   8.0500      True       False        True
..      ...   ...    ...    ...      ...       ...         ...         ...
886       2  27.0      0      0  13.0000      True       False        True
887       1  19.0      0      0  30.0000     False       False        True
888       3  28.0      1      2  23.4500     False       False        True
889       1  26.0      0      0  30.0000      True       False       False
890       3  32.0      0      0   7.7500      True        True       False

[891 rows x 8 columns]

In [68]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
log_pred = log_model.predict(X_test)

In [ ]:
print(
    "Logistic Regression Accuracy:",
    accuracy_score(y_test, log_pred)
)

Accuracy: 0.8212290502793296

In [80]:
age = int(input("Age: "))
sex = input("Sex (male/female): ").lower()

pclass = int(
    input("Passenger Class (1, 2, or 3): ")
)

sibsp = int(
    input("Number of siblings/spouses aboard: ")
)

parch = int(
    input("Number of parents/children aboard: ")
)

fare = float(
    input("Ticket fare: ")
)

embarked = input(" C-Cherbourg France 🇫🇷\nQ-Queenstown\nS-Southampton England\n").upper()

In [81]:
user_data = {
    'Pclass': pclass,
    'Age': age,
    'SibSp': sibsp,
    'Parch': parch,
    'Fare': fare,
    'Sex_male': 1 if sex == "male" else 0,
    'Embarked_Q': 1 if embarked == "Q" else 0,
    'Embarked_S': 1 if embarked == "S" else 0
}

In [82]:
user_df = pd.DataFrame([user_data])

In [83]:
feature_columns = X.columns

user_df = user_df.reindex(
    columns=feature_columns,
    fill_value=0
)

In [ ]:
prediction = log_model.predict(user_df)

In [ ]:
if prediction[0] == 1:
    print("Prediction: Survived")
else:
    print("Prediction: Quite Cooked")

Prediction: Did Not Survive