In [55]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

In [56]:
data = pd.read_csv("airbnb-data.csv");

#from the info, reviews per month has a lot of NAN values
data['reviews_per_month'] = data['reviews_per_month'].fillna(0);

#replace all nan values in name with unknown
data['name'] = data['name'].fillna("Unknown");

#drop the id and host_name columns because they aren't really needed here
# Drop early, right after your existing drops
data.drop(['id', 'host_name', 'name', 'last_review', 'host_id', 
           'neighbourhood', 'neighbourhood_group',
           'calculated_host_listings_count'], 
          axis=1, inplace=True)

#removes outliers which will lead to a right skewed distribution
data = data[data['price'] < 500]

data

,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,availability_365
0,40.64749,-73.97237,Private room,149,1,9,0.21,365
1,40.75362,-73.98377,Entire home/apt,225,1,45,0.38,355
2,40.80902,-73.94190,Private room,150,3,0,0.00,365
3,40.68514,-73.95976,Entire home/apt,89,1,270,4.64,194
4,40.79851,-73.94399,Entire home/apt,80,10,9,0.10,0
...,...,...,...,...,...,...,...,...
48890,40.67853,-73.94995,Private room,70,2,0,0.00,9
48891,40.70184,-73.93317,Private room,40,4,0,0.00,36
48892,40.81475,-73.94867,Entire home/apt,115,10,0,0.00,27
48893,40.75751,-73.99112,Shared room,55,1,0,0.00,2
48894,40.76404,-73.98933,Private room,90,7,0,0.00,23

In [57]:
data['price'] = np.log1p(data['price'])

In [58]:
#Split into features (x) and target (y)
X = data.drop('price', axis=1)
y = data['price']

In [59]:
data.dtypes

latitude             float64
longitude            float64
room_type                str
price                float64
minimum_nights         int64
number_of_reviews      int64
reviews_per_month    float64
availability_365       int64
dtype: object

In [60]:
#convert non-numeric types
X = pd.get_dummies(X, drop_first=True)
feature_columns = X.columns

In [61]:
X

,latitude,longitude,minimum_nights,number_of_reviews,reviews_per_month,availability_365,room_type_Private room,room_type_Shared room
0,40.64749,-73.97237,1,9,0.21,365,True,False
1,40.75362,-73.98377,1,45,0.38,355,False,False
2,40.80902,-73.94190,3,0,0.00,365,True,False
3,40.68514,-73.95976,1,270,4.64,194,False,False
4,40.79851,-73.94399,10,9,0.10,0,False,False
...,...,...,...,...,...,...,...,...
48890,40.67853,-73.94995,2,0,0.00,9,True,False
48891,40.70184,-73.93317,4,0,0.00,36,True,False
48892,40.81475,-73.94867,10,0,0.00,27,False,False
48893,40.75751,-73.99112,1,0,0.00,2,False,True
48894,40.76404,-73.98933,7,0,0.00,23,True,False

In [62]:
#Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [63]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    verbose=2
)

rf_model.fit(X_train, y_train)

building tree 1 of 100
building tree 2 of 100
building tree 3 of 100
building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100

[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:    5.2s

building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82 of 100
building tree 83 of 100
building tree 84 of 100
building tree 85 of 100
building tree 86 of 100
building tree 87 of 100
building tree 88 of 100
building tree 89 of 100
building tree 90 of 100
building tree 91 of 100
building tree 92 of 100
building tree 93 of 100
building tree 94 of 100
building tree 95 of 100
building tree 96 of 100
building tree 97 of 100
building tree 98 of 100
building tree 99 of 100
building tree 100 of 100

[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:   12.7s finished

RandomForestRegressor(random_state=42, verbose=2)

In [64]:
rf_pred = rf_model.predict(X_test)

[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.3s finished

In [65]:
print("RANDOM FOREST RESULTS")
print("MAE:", mean_absolute_error(y_test, rf_pred))
print("R2:", r2_score(y_test, rf_pred))

RANDOM FOREST RESULTS
MAE: 0.28312791596087017
R2: 0.6270012973107837

In [66]:
latitude = float(input("Enter latitude: "))
longitude = float(input("Enter longitude: "))
minimum_nights = int(input("Minimum nights: "))
number_of_reviews = int(input("Number of reviews: "))
reviews_per_month = float(input("Reviews per month: "))
availability_365 = int(input("Availability in 365 days: "))
room_type = input("Room type (Entire home/apt, Private room, Shared room): ")

user_data = {
    'latitude': latitude,
    'longitude': longitude,
    'minimum_nights': minimum_nights,
    'number_of_reviews': number_of_reviews,
    'reviews_per_month': reviews_per_month,
    'availability_365': availability_365,
    'room_type': room_type
}

In [67]:
user_df = pd.DataFrame([user_data])

user_df = pd.get_dummies(user_df)

user_df = user_df.reindex(columns=feature_columns, fill_value=0)

In [68]:
prediction = rf_model.predict(user_df)
final_price = np.expm1(prediction[0])

[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished

In [69]:
print("Predicted Airbnb Price:", round(final_price, 2))

Predicted Airbnb Price: 116.64