In [14]:
import pandas as pd

In [15]:


#a list of strings
info = ['CSC', '102', 'is', 'the', 'best', 'course', 'ever']

#call the dataframe constructor on info
df = pd.DataFrame(info)

df

        0
0     CSC
1     102
2      is
3     the
4    best
5  course
6    ever

In [16]:
data = {
    'Name' : ['Angela', 'Precious', 'Luis', 'Ade'],
    'Age' : [20, 21, 19, 18]
}

df = pd.DataFrame(data);

df

       Name  Age
0    Angela   20
1  Precious   21
2      Luis   19
3       Ade   18

In [17]:
data = {
    'Name' : ['Clem', 'Prince', 'Edward', 'Adele'],
    'Age' : [27, 24, 22, 32],
    'Address' : ['Abuja', 'Kano', 'Minna', 'Lagos'],
    'Qualification' : ['MSc', 'MA', 'MCA', 'PhD']
}

df = pd.DataFrame(data);

df[['Name', 'Qualification', 'Address']]

     Name Qualification Address
0    Clem           MSc   Abuja
1  Prince            MA    Kano
2  Edward           MCA   Minna
3   Adele           PhD   Lagos

In [18]:
df.iloc[1,3]

'MA'

In [19]:
data = pd.read_csv('iris.csv');

data

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [20]:
df = data.iloc[0] #select first row

df

sepal_length            5.1
sepal_width             3.5
petal_length            1.4
petal_width             0.2
class           Iris-setosa
Name: 0, dtype: object

In [21]:
df = data.head(2)

df

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa

In [22]:
# loop over rows
for index, values in data.iterrows():
    print(index);
    print(values);

0
sepal_length            5.1
sepal_width             3.5
petal_length            1.4
petal_width             0.2
class           Iris-setosa
Name: 0, dtype: object
1
sepal_length            4.9
sepal_width             3.0
petal_length            1.4
petal_width             0.2
class           Iris-setosa
Name: 1, dtype: object
2
sepal_length            4.7
sepal_width             3.2
petal_length            1.3
petal_width             0.2
class           Iris-setosa
Name: 2, dtype: object
3
sepal_length            4.6
sepal_width             3.1
petal_length            1.5
petal_width             0.2
class           Iris-setosa
Name: 3, dtype: object
4
sepal_length            5.0
sepal_width             3.6
petal_length            1.4
petal_width             0.2
class           Iris-setosa
Name: 4, dtype: object
5
sepal_length            5.4
sepal_width             3.9
petal_length            1.7
petal_width             0.4
class           Iris-setosa
Name: 5, dtype: object
6
sepal_length            4.6
sepal_width             3.4
petal_length            1.4
petal_width             0.3
class           Iris-setosa
Name: 6, dtype: object
7
sepal_length            5.0
sepal_width             3.4
petal_length            1.5
petal_width             0.2
class           Iris-setosa
Name: 7, dtype: object
8
sepal_length            4.4
sepal_width             2.9
petal_length            1.4
petal_width             0.2
class           Iris-setosa
Name: 8, dtype: object
9
sepal_length            4.9
sepal_width             3.1
petal_length            1.5
petal_width             0.1
class           Iris-setosa
Name: 9, dtype: object
10
sepal_length            5.4
sepal_width             3.7
petal_length            1.5
petal_width             0.2
class           Iris-setosa
Name: 10, dtype: object
11
sepal_length            4.8
sepal_width             3.4
petal_length            1.6
petal_width             0.2
class           Iris-setosa
Name: 11, dtype: object
12
sepal_length            4.8
sepal_width             3.0
petal_length            1.4
petal_width             0.1
class           Iris-setosa
Name: 12, dtype: object
13
sepal_length            4.3
sepal_width             3.0
petal_length            1.1
petal_width             0.1
class           Iris-setosa
Name: 13, dtype: object
14
sepal_length            5.8
sepal_width             4.0
petal_length            1.2
petal_width             0.2
class           Iris-setosa
Name: 14, dtype: object
15
sepal_length            5.7
sepal_width             4.4
petal_length            1.5
petal_width             0.4
class           Iris-setosa
Name: 15, dtype: object
16
sepal_length            5.4
sepal_width             3.9
petal_length            1.3
petal_width             0.4
class           Iris-setosa
Name: 16, dtype: object
17
sepal_length            5.1
sepal_width             3.5
petal_length            1.4
petal_width             0.3
class           Iris-setosa
Name: 17, dtype: object
18
sepal_length            5.7
sepal_width             3.8
petal_length            1.7
petal_width             0.3
class           Iris-setosa
Name: 18, dtype: object
19
sepal_length            5.1
sepal_width             3.8
petal_length            1.5
petal_width             0.3
class           Iris-setosa
Name: 19, dtype: object
20
sepal_length            5.4
sepal_width             3.4
petal_length            1.7
petal_width             0.2
class           Iris-setosa
Name: 20, dtype: object
21
sepal_length            5.1
sepal_width             3.7
petal_length            1.5
petal_width             0.4
class           Iris-setosa
Name: 21, dtype: object
22
sepal_length            4.6
sepal_width             3.6
petal_length            1.0
petal_width             0.2
class           Iris-setosa
Name: 22, dtype: object
23
sepal_length            5.1
sepal_width             3.3
petal_length            1.7
petal_width             0.5
class           Iris-setosa
Name: 23, dtype: object
24
sepal_length            4.8
sepal_width             3.4
petal_length            1.9
petal_width             0.2
class           Iris-setosa
Name: 24, dtype: object
25
sepal_length            5.0
sepal_width             3.0
petal_length            1.6
petal_width             0.2
class           Iris-setosa
Name: 25, dtype: object
26
sepal_length            5.0
sepal_width             3.4
petal_length            1.6
petal_width             0.4
class           Iris-setosa
Name: 26, dtype: object
27
sepal_length            5.2
sepal_width             3.5
petal_length            1.5
petal_width             0.2
class           Iris-setosa
Name: 27, dtype: object
28
sepal_length            5.2
sepal_width             3.4
petal_length            1.4
petal_width             0.2
class           Iris-setosa
Name: 28, dtype: object
29
sepal_length            4.7
sepal_width             3.2
petal_length            1.6
petal_width             0.2
class           Iris-setosa
Name: 29, dtype: object
30
sepal_length            4.8
sepal_width             3.1
petal_length            1.6
petal_width             0.2
class           Iris-setosa
Name: 30, dtype: object
31
sepal_length            5.4
sepal_width             3.4
petal_length            1.5
petal_width             0.4
class           Iris-setosa
Name: 31, dtype: object
32
sepal_length            5.2
sepal_width             4.1
petal_length            1.5
petal_width             0.1
class           Iris-setosa
Name: 32, dtype: object
33
sepal_length            5.5
sepal_width             4.2
petal_length            1.4
petal_width             0.2
class           Iris-setosa
Name: 33, dtype: object
34
sepal_length            4.9
sepal_width             3.1
petal_length            1.5
petal_width             0.1
class           Iris-setosa
Name: 34, dtype: object
35
sepal_length            5.0
sepal_width             3.2
petal_length            1.2
petal_width             0.2
class           Iris-setosa
Name: 35, dtype: object
36
sepal_length            5.5
sepal_width             3.5
petal_length            1.3
petal_width             0.2
class           Iris-setosa
Name: 36, dtype: object
37
sepal_length            4.9
sepal_width             3.1
petal_length            1.5
petal_width             0.1
class           Iris-setosa
Name: 37, dtype: object
38
sepal_length            4.4
sepal_width             3.0
petal_length            1.3
petal_width             0.2
class           Iris-setosa
Name: 38, dtype: object
39
sepal_length            5.1
sepal_width             3.4
petal_length            1.5
petal_width             0.2
class           Iris-setosa
Name: 39, dtype: object
40
sepal_length            5.0
sepal_width             3.5
petal_length            1.3
petal_width             0.3
class           Iris-setosa
Name: 40, dtype: object
41
sepal_length            4.5
sepal_width             2.3
petal_length            1.3
petal_width             0.3
class           Iris-setosa
Name: 41, dtype: object
42
sepal_length            4.4
sepal_width             3.2
petal_length            1.3
petal_width             0.2
class           Iris-setosa
Name: 42, dtype: object
43
sepal_length            5.0
sepal_width             3.5
petal_length            1.6
petal_width             0.6
class           Iris-setosa
Name: 43, dtype: object
44
sepal_length            5.1
sepal_width             3.8
petal_length            1.9
petal_width             0.4
class           Iris-setosa
Name: 44, dtype: object
45
sepal_length            4.8
sepal_width             3.0
petal_length            1.4
petal_width             0.3
class           Iris-setosa
Name: 45, dtype: object
46
sepal_length            5.1
sepal_width             3.8
petal_length            1.6
petal_width             0.2
class           Iris-setosa
Name: 46, dtype: object
47
sepal_length            4.6
sepal_width             3.2
petal_length            1.4
petal_width             0.2
class           Iris-setosa
Name: 47, dtype: object
48
sepal_length            5.3
sepal_width             3.7
petal_length            1.5
petal_width             0.2
class           Iris-setosa
Name: 48, dtype: object
49
sepal_length            5.0
sepal_width             3.3
petal_length            1.4
petal_width             0.2
class           Iris-setosa
Name: 49, dtype: object
50
sepal_length                7.0
sepal_width                 3.2
petal_length                4.7
petal_width                 1.4
class           Iris-versicolor
Name: 50, dtype: object
51
sepal_length                6.4
sepal_width                 3.2
petal_length                4.5
petal_width                 1.5
class           Iris-versicolor
Name: 51, dtype: object
52
sepal_length                6.9
sepal_width                 3.1
petal_length                4.9
petal_width                 1.5
class           Iris-versicolor
Name: 52, dtype: object
53
sepal_length                5.5
sepal_width                 2.3
petal_length                4.0
petal_width                 1.3
class           Iris-versicolor
Name: 53, dtype: object
54
sepal_length                6.5
sepal_width                 2.8
petal_length                4.6
petal_width                 1.5
class           Iris-versicolor
Name: 54, dtype: object
55
sepal_length                5.7
sepal_width                 2.8
petal_length                4.5
petal_width                 1.3
class           Iris-versicolor
Name: 55, dtype: object
56
sepal_length                6.3
sepal_width                 3.3
petal_length                4.7
petal_width                 1.6
class           Iris-versicolor
Name: 56, dtype: object
57
sepal_length                4.9
sepal_width                 2.4
petal_length                3.3
petal_width                 1.0
class           Iris-versicolor
Name: 57, dtype: object
58
sepal_length                6.6
sepal_width                 2.9
petal_length                4.6
petal_width                 1.3
class           Iris-versicolor
Name: 58, dtype: object
59
sepal_length                5.2
sepal_width                 2.7
petal_length                3.9
petal_width                 1.4
class           Iris-versicolor
Name: 59, dtype: object
60
sepal_length                5.0
sepal_width                 2.0
petal_length                3.5
petal_width                 1.0
class           Iris-versicolor
Name: 60, dtype: object
61
sepal_length                5.9
sepal_width                 3.0
petal_length                4.2
petal_width                 1.5
class           Iris-versicolor
Name: 61, dtype: object
62
sepal_length                6.0
sepal_width                 2.2
petal_length                4.0
petal_width                 1.0
class           Iris-versicolor
Name: 62, dtype: object
63
sepal_length                6.1
sepal_width                 2.9
petal_length                4.7
petal_width                 1.4
class           Iris-versicolor
Name: 63, dtype: object
64
sepal_length                5.6
sepal_width                 2.9
petal_length                3.6
petal_width                 1.3
class           Iris-versicolor
Name: 64, dtype: object
65
sepal_length                6.7
sepal_width                 3.1
petal_length                4.4
petal_width                 1.4
class           Iris-versicolor
Name: 65, dtype: object
66
sepal_length                5.6
sepal_width                 3.0
petal_length                4.5
petal_width                 1.5
class           Iris-versicolor
Name: 66, dtype: object
67
sepal_length                5.8
sepal_width                 2.7
petal_length                4.1
petal_width                 1.0
class           Iris-versicolor
Name: 67, dtype: object
68
sepal_length                6.2
sepal_width                 2.2
petal_length                4.5
petal_width                 1.5
class           Iris-versicolor
Name: 68, dtype: object
69
sepal_length                5.6
sepal_width                 2.5
petal_length                3.9
petal_width                 1.1
class           Iris-versicolor
Name: 69, dtype: object
70
sepal_length                5.9
sepal_width                 3.2
petal_length                4.8
petal_width                 1.8
class           Iris-versicolor
Name: 70, dtype: object
71
sepal_length                6.1
sepal_width                 2.8
petal_length                4.0
petal_width                 1.3
class           Iris-versicolor
Name: 71, dtype: object
72
sepal_length                6.3
sepal_width                 2.5
petal_length                4.9
petal_width                 1.5
class           Iris-versicolor
Name: 72, dtype: object
73
sepal_length                6.1
sepal_width                 2.8
petal_length                4.7
petal_width                 1.2
class           Iris-versicolor
Name: 73, dtype: object
74
sepal_length                6.4
sepal_width                 2.9
petal_length                4.3
petal_width                 1.3
class           Iris-versicolor
Name: 74, dtype: object
75
sepal_length                6.6
sepal_width                 3.0
petal_length                4.4
petal_width                 1.4
class           Iris-versicolor
Name: 75, dtype: object
76
sepal_length                6.8
sepal_width                 2.8
petal_length                4.8
petal_width                 1.4
class           Iris-versicolor
Name: 76, dtype: object
77
sepal_length                6.7
sepal_width                 3.0
petal_length                5.0
petal_width                 1.7
class           Iris-versicolor
Name: 77, dtype: object
78
sepal_length                6.0
sepal_width                 2.9
petal_length                4.5
petal_width                 1.5
class           Iris-versicolor
Name: 78, dtype: object
79
sepal_length                5.7
sepal_width                 2.6
petal_length                3.5
petal_width                 1.0
class           Iris-versicolor
Name: 79, dtype: object
80
sepal_length                5.5
sepal_width                 2.4
petal_length                3.8
petal_width                 1.1
class           Iris-versicolor
Name: 80, dtype: object
81
sepal_length                5.5
sepal_width                 2.4
petal_length                3.7
petal_width                 1.0
class           Iris-versicolor
Name: 81, dtype: object
82
sepal_length                5.8
sepal_width                 2.7
petal_length                3.9
petal_width                 1.2
class           Iris-versicolor
Name: 82, dtype: object
83
sepal_length                6.0
sepal_width                 2.7
petal_length                5.1
petal_width                 1.6
class           Iris-versicolor
Name: 83, dtype: object
84
sepal_length                5.4
sepal_width                 3.0
petal_length                4.5
petal_width                 1.5
class           Iris-versicolor
Name: 84, dtype: object
85
sepal_length                6.0
sepal_width                 3.4
petal_length                4.5
petal_width                 1.6
class           Iris-versicolor
Name: 85, dtype: object
86
sepal_length                6.7
sepal_width                 3.1
petal_length                4.7
petal_width                 1.5
class           Iris-versicolor
Name: 86, dtype: object
87
sepal_length                6.3
sepal_width                 2.3
petal_length                4.4
petal_width                 1.3
class           Iris-versicolor
Name: 87, dtype: object
88
sepal_length                5.6
sepal_width                 3.0
petal_length                4.1
petal_width                 1.3
class           Iris-versicolor
Name: 88, dtype: object
89
sepal_length                5.5
sepal_width                 2.5
petal_length                4.0
petal_width                 1.3
class           Iris-versicolor
Name: 89, dtype: object
90
sepal_length                5.5
sepal_width                 2.6
petal_length                4.4
petal_width                 1.2
class           Iris-versicolor
Name: 90, dtype: object
91
sepal_length                6.1
sepal_width                 3.0
petal_length                4.6
petal_width                 1.4
class           Iris-versicolor
Name: 91, dtype: object
92
sepal_length                5.8
sepal_width                 2.6
petal_length                4.0
petal_width                 1.2
class           Iris-versicolor
Name: 92, dtype: object
93
sepal_length                5.0
sepal_width                 2.3
petal_length                3.3
petal_width                 1.0
class           Iris-versicolor
Name: 93, dtype: object
94
sepal_length                5.6
sepal_width                 2.7
petal_length                4.2
petal_width                 1.3
class           Iris-versicolor
Name: 94, dtype: object
95
sepal_length                5.7
sepal_width                 3.0
petal_length                4.2
petal_width                 1.2
class           Iris-versicolor
Name: 95, dtype: object
96
sepal_length                5.7
sepal_width                 2.9
petal_length                4.2
petal_width                 1.3
class           Iris-versicolor
Name: 96, dtype: object
97
sepal_length                6.2
sepal_width                 2.9
petal_length                4.3
petal_width                 1.3
class           Iris-versicolor
Name: 97, dtype: object
98
sepal_length                5.1
sepal_width                 2.5
petal_length                3.0
petal_width                 1.1
class           Iris-versicolor
Name: 98, dtype: object
99
sepal_length                5.7
sepal_width                 2.8
petal_length                4.1
petal_width                 1.3
class           Iris-versicolor
Name: 99, dtype: object
100
sepal_length               6.3
sepal_width                3.3
petal_length               6.0
petal_width                2.5
class           Iris-virginica
Name: 100, dtype: object
101
sepal_length               5.8
sepal_width                2.7
petal_length               5.1
petal_width                1.9
class           Iris-virginica
Name: 101, dtype: object
102
sepal_length               7.1
sepal_width                3.0
petal_length               5.9
petal_width                2.1
class           Iris-virginica
Name: 102, dtype: object
103
sepal_length               6.3
sepal_width                2.9
petal_length               5.6
petal_width                1.8
class           Iris-virginica
Name: 103, dtype: object
104
sepal_length               6.5
sepal_width                3.0
petal_length               5.8
petal_width                2.2
class           Iris-virginica
Name: 104, dtype: object
105
sepal_length               7.6
sepal_width                3.0
petal_length               6.6
petal_width                2.1
class           Iris-virginica
Name: 105, dtype: object
106
sepal_length               4.9
sepal_width                2.5
petal_length               4.5
petal_width                1.7
class           Iris-virginica
Name: 106, dtype: object
107
sepal_length               7.3
sepal_width                2.9
petal_length               6.3
petal_width                1.8
class           Iris-virginica
Name: 107, dtype: object
108
sepal_length               6.7
sepal_width                2.5
petal_length               5.8
petal_width                1.8
class           Iris-virginica
Name: 108, dtype: object
109
sepal_length               7.2
sepal_width                3.6
petal_length               6.1
petal_width                2.5
class           Iris-virginica
Name: 109, dtype: object
110
sepal_length               6.5
sepal_width                3.2
petal_length               5.1
petal_width                2.0
class           Iris-virginica
Name: 110, dtype: object
111
sepal_length               6.4
sepal_width                2.7
petal_length               5.3
petal_width                1.9
class           Iris-virginica
Name: 111, dtype: object
112
sepal_length               6.8
sepal_width                3.0
petal_length               5.5

In [23]:
#loop over columns

print(data.columns);

for col in data.columns:
    print(data[col][3]) #third element of the column

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='str')
4.6
3.1
1.5
0.2
Iris-setosa

In [24]:
#save to csv file

#here, record is a dict of lists
record = {
    'Name' : ['Abel', 'Kamsi', 'Oyode', 'Chinelo'],
    'Qualification' : ['MBA', 'BCA', 'M. Tech', 'MBA'],
    'Score' : [90, 40, 80, 98]
}

df = pd.DataFrame(record);

df.to_csv('record.csv');